document.write('<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0" width="223" height="298" id="menu" align="middle">')
document.write('<param name="allowScriptAccess" value="sameDomain" />')
document.write('<param name="movie" value="/menu.swf" />')
document.write('<param name="quality" value="high" />')
document.write('<param name="bgcolor" value="#ffffff" />')
document.write('<param name="menu" value="false">')
document.write('<embed src="/menu.swf" menu="false" quality="high" bgcolor="#ffffff" width="223" height="298" name="menu"  swliveconnect="true" align="middle" allowScriptAccess="sameDomain" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" /></object>')