document.write('<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0" width="124" height="35">')
document.write('<param name="movie" value="/swf/rightglow.swf">')
document.write('<param name="quality" value="high">')
document.write('<param name="menu" value="false">')
document.write('<embed src="/swf/rightglow.swf" menu="false" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" width="124" height="35"></embed></object>')